# Reference https://github.com/lowlighter/metrics/blob/master/action.yml

name: Metrics

on:
  schedule: [{cron: "0 10 * * *"}]
  workflow_dispatch:
  # push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: edisoft00
          template: classic
          config_timezone: America/Chicago
          base: header, activity, community, repositories
          repositories_affiliations: owner, collaborator

          # Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
