# Reference https://github.com/lowlighter/metrics/blob/master/action.yml

name: Metrics

on:
  schedule:
    - cron: '50 5 * 1-2,11-12 *' # Winter
    - cron: '50 4 * 3-10 *' # Summer

  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - .github/workflows/metrics.yml

concurrency:
  group: metrics
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          # GitHub
          token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: assets
          committer_message: "build: update metrics report"
          filename: metrics.svg

          # Options
          user: edisoft00
          template: classic
          config_timezone: America/Chicago
          base: header, activity, community, repositories
          repositories_affiliations: owner, collaborator

          # Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
